/////////////////////////////////////////////////////////////////////////////
//
// include/objtype.inc - Object Type definitions
//
/////////////////////////////////////////////////////////////////////////////


///////////////////
//  Reagents
///////////////////

Const UOBJ_BATWING			:= 0x0F78;
Const UOBJ_BLACKMOOR		:= 0x0f79;
Const UOBJ_BLACK_PEARL		:= 0x0F7A;
Const UOBJ_BLOOD_MOSS		:= 0x0F7B;
Const UOBJ_BLOODSPAWN		:= 0x0F7C;
Const UOBJ_VIAL_OF_BLOOD		:= 0x0F7D;
Const UOBJ_BONE			:= 0x0F7E;
Const UOBJ_BRIMSTONE		:= 0x0F7F;
Const UOBJ_DAEMON_BONE		:= 0x0F80;
Const UOBJ_FERTILE_DIRT		:= 0x0F81;
Const UOBJ_DRAGONS_BLOOD		:= 0x0F82;
Const UOBJ_EXECUTIONERS_CAP	:= 0x0F83;
Const UOBJ_GARLIC			:= 0x0F84;
Const UOBJ_GINSENG			:= 0x0F85;
Const UOBJ_MANDRAKE_ROOT		:= 0x0F86;
Const UOBJ_EYE_OF_NEWT		:= 0x0F87;
Const UOBJ_NIGHTSHADE		:= 0x0F88;
Const UOBJ_OBSIDIAN			:= 0x0F89;
Const UOBJ_PIG_IRON			:= 0x0F8A;
Const UOBJ_PUMICE			:= 0x0F8B;
Const UOBJ_SULFUROUS_ASH		:= 0x0F8C;
Const UOBJ_SPIDER_SILK		:= 0x0F8D;
Const UOBJ_SERPENT_SCALE		:= 0x0F8E;
Const UOBJ_VOLCANIC_ASH		:= 0x0F8F;
Const UOBJ_DEAD_WOOD		:= 0x0F90;
Const UOBJ_WYRMS_HEART		:= 0x0F91;

Const UOBJ_REAPER_HEARTWOOD	:= 0x1706f;
Const UOBJ_ENT_HEARTWOOD		:= 0x1706e;
Const UOBJ_ENCHANTED_BONE	:= 0x1A153;



///////////////////
//  potions
///////////////////

Const UOBJ_LIGHT_HEAL_POTION		:= 0xDC01;
Const UOBJ_HEAL_POTION			:= 0xDC02;
Const UOBJ_GREATER_HEAL_POTION	:= 0xDC03;
Const UOBJ_LESSER_POISON_POTION	:= 0xDC04;
Const UOBJ_POISON_POTION			:= 0xDC05;
Const UOBJ_GREATER_POISON_POTION	:= 0xDC06;
Const UOBJ_DEADLY_POISON_POTION	:= 0xDC17;
Const UOBJ_LESSER_EXPLOSION_POTION := 0xDC08;
Const UOBJ_EXPLOSION_POTION		:= 0xDC09;
Const UOBJ_GREATER_EXPLOSION_POTION:= 0xDC07;
Const UOBJ_LESSER_AGILITY_POTION	:= 0xDC0B;
Const UOBJ_AGILITY_POTION		:= 0xDC0C;
Const UOBJ_GREATER_AGILITY_POTION	:= 0xDC0D;
Const UOBJ_REFRESH_POTION		:= 0xDC0E;
Const UOBJ_FULL_REFRESH_POTION	:= 0xDC0F;
Const UOBJ_LESSER_STRENGTH_POTION	:= 0xDC10;
Const UOBJ_STRENGTH_POTION		:= 0xDC11;
Const UOBJ_GREATER_STRENGTH_POTION	:= 0xDC12;
Const UOBJ_LESSER_CURE_POTION		:= 0xDC14;
Const UOBJ_CURE_POTION			:= 0xDC15;
Const UOBJ_GREATER_CURE_POTION	:= 0xDC16;
Const UOBJ_NIGHTSIGHT_POTION		:= 0xDCE6;
Const UOBJ_NEW_POTION			:= 0x17059;
Const UOBJ_ELIXER_POTION			:= 0xdc2b;
Const UOBJ_POTION_KEG			:= 0x1940;



///////////////////
//  Magic-type items
///////////////////

Const UOBJ_SPELLBOOK		:= 0x0EFA;
Const UOBJ_CODEX_DAMNORUM	:= 0xA100;
Const UOBJ_DRUIDBAG			:= 0x1706b;
Const UOBJ_RECALL_RUNE		:= 0x1F14;
Const UOBJ_RUNEBOOK			:= 0x16100;

Const UOBJ_MORTAR			:= 0x0e9b;
Const UOBJ_HEATINGSTAND		:= 0x1849;


///////////////////
//  Gems
///////////////////

Const UOBJ_GEM_AMBER		:= 0x0F25;
Const UOBJ_GEM_STAR_SAPPHIRE	:= 0x0F0F;
Const UOBJ_GEM_EMERALD		:= 0x0F10;
Const UOBJ_GEM_SAPPHIRE		:= 0x0F11;
Const UOBJ_GEM_RUBY			:= 0x0F13;
Const UOBJ_GEM_CITRINE		:= 0x0F15;
Const UOBJ_GEM_AMETHYST		:= 0x0F16;
Const UOBJ_GEM_TOURMALINE	:= 0x0F18;
Const UOBJ_GEM_DIAMOND		:= 0x0F30;
const UOBJ_GEM_START		:= 0x0F0F;
const UOBJ_GEM_END			:= 0x0f30;




///////////////////
//  Ore and ingots
///////////////////

const UOBJ_IRON_ORE			:= 0x16009;
const UOBJ_BRONZE_ORE		:= 0x1600a;  
const UOBJ_DULLCOPPER_ORE	:= 0x1600b;
const UOBJ_COPPER_ORE		:= 0x1600c;
const UOBJ_ONYX_ORE			:= 0x1600d;
const UOBJ_PYRITE_ORE		:= 0x1600e;
const UOBJ_MALACHITE_ORE		:= 0x1600f;
const UOBJ_AZURITE_ORE		:= 0x16010;
Const UOBJ_BLUESTEEL_ORE		:= 0x17061;
Const UOBJ_RUBYSTEEL_ORE		:= 0x17062;

const UOBJ_IRON_INGOT		:= 0x16011;
const UOBJ_BRONZE_INGOT		:= 0x16012;  
const UOBJ_DULLCOPPER_INGOT	:= 0x16013;
const UOBJ_COPPER_INGOT		:= 0x16014;
const UOBJ_ONYX_INGOT		:= 0x16015;
const UOBJ_PYRITE_INGOT		:= 0x16016;
const UOBJ_MALACHITE_INGOT	:= 0x16017;
const UOBJ_AZURITE_INGOT	:= 0x16018;
Const UOBJ_BLUESTEEL_INGOT	:= 0x17063;
Const UOBJ_RUBYSTEEL_INGOT	:= 0x17064;

Const UOBJ_GOLD_COIN		:= 0x0eed;
Const UOBJ_GOLD_INGOT		:= 0x1be9;
const UOBJ_CLAY				:= 0xee19;
const UOBJ_SAND			:= 0xee18;
const UOBJ_GLASS			:= 0xee20;
const UOBJ_PORCELAIN			:= 0xee21;

const UOBJ_GRANITE_STONE		:= 0x16300;
const UOBJ_BRONZE_STONE		:= 0x16301;  
const UOBJ_DULLCOPPER_STONE	:= 0x16302;
const UOBJ_COPPER_STONE		:= 0x16303;
const UOBJ_ONYX_STONE		:= 0x16304;
const UOBJ_PYRITE_STONE		:= 0x16305;
const UOBJ_MALACHITE_STONE	:= 0x16306;
const UOBJ_AZURITE_STONE		:= 0x16307;
Const UOBJ_BLUESTEEL_STONE	:= 0x16308;
Const UOBJ_RUBYSTEEL_STONE	:= 0x16309;
Const UOBJ_SAND_STONE		:= 0x1630a;
Const UOBJ_MARBLE_STONE		:= 0x1630b;



///////////////////
//  Tailoring items
///////////////////

Const UOBJ_SEWING_KIT		:= 0x0F9D;
Const UOBJ_BOLT_OF_CLOTH		:= 0x0F95;
Const UOBJ_CLOTH			:= 0x1765;
Const UOBJ_WOOL			:= 0x0df8;
Const UOBJ_HIDE			:= 0x1078;
Const UOBJ_BROWN_HIDE		:= 0x17050;
Const UOBJ_RED_HIDE			:= 0x17051;
Const UOBJ_BLUE_HIDE		:= 0x17052;
Const UOBJ_GREEN_HIDE		:= 0x17053;
Const UOBJ_SILVER_HIDE		:= 0x17054;

Const UOBJ_THREAD1			:= 0x0FA0;
Const UOBJ_THREAD2			:= 0x0FA1;
Const UOBJ_YARN			:= 0x0E1D;
Const UOBJ_BOLT_START		:= 0x0F95;
Const UOBJ_BOLT_END			:= 0x0F9C;
Const UOBJ_CLOTH_START		:= 0x175D;
Const UOBJ_CLOTH_END		:= 0x1768;
Const UOBJ_COLORED_HIDE_START	:= 0x17050;
Const UOBJ_COLORED_HIDE_END	:= 0x17054;




///////////////////
//  Footwear
///////////////////

Const UOBJ_SANDALS			:= 0x170D;
Const UOBJ_SHOES			:= 0x170F;
Const UOBJ_BOOTS			:= 0x170B;
Const UOBJ_THIGH_BOOTS		:= 0x1711;




///////////////////
//  Containers
///////////////////

Const UOBJ_BACKPACK			:= 0x0E75;
Const UOBJ_BAG				:= 0x0E76;
Const UOBJ_POUCH			:= 0x0E79;
Const UOBJ_BASKET			:= 0x0990;
Const UOBJ_PICNIC_BASKET		:= 0x0E7A;
Const UOBJ_WOODEN_BOX_1		:= 0x0E7D;
Const UOBJ_WOODEN_BOX_2		:= 0x09AA;
Const UOBJ_TRASHBARREL		:= 0x17057;



///////////////////
//  Tinkering items
///////////////////

Const UOBJ_TINKER_TOOLS		:= 0x1EBC;
Const UOBJ_TINKER_TOOLKIT		:= 0x1eb8;
Const UOBJ_CLOCK			:= 0x104c;
Const UOBJ_CLOCK_FRAME		:= 0x104e;
Const UOBJ_CLOCK_PARTS		:= 0x104f;
Const UOBJ_AXLE_AND_GEARS	:= 0x1051;
Const UOBJ_GEARS			:= 0x1053;
Const UOBJ_HINGE			:= 0x1055;
Const UOBJ_SEXTANT			:= 0x1057;
Const UOBJ_SEXTANT_PARTS	:=	0x1059;
Const UOBJ_AXLE				:= 0x105b;
Const UOBJ_SPRINGS			:= 0x105d;

Const UOBJ_WAX				:= 0x1422;
Const UOBJ_EMPTY_KETTLE		:= 0x09ed;
Const UOBJ_KETTLE_OF_WAX	:= 0x142a;
Const UOBJ_DIPPING_STICK		:= 0x1428;
Const UOBJ_SKULL			:= 0x1ae2;




///////////////////
//  Blacksmithy items
///////////////////

Const UOBJ_ANVIL1			:= 0x0FAF;
Const UOBJ_ANVIL2			:= 0x0FB0;
Const UOBJ_SMALL_FORGE		:= 0x0FB1;
Const UOBJ_FORGE_START		:= 0x197A;
Const UOBJ_FORGE_END		:= 0x19A9;
Const UOBJ_ELVEN_FORGE		:= 0x2dd8;
Const UOBJ_SOULFORGE		:= 0x423f;
Const UOBJ_SOULFORGE_NW		:= 0x4268;
Const UOBJ_SOULFORGE_NE		:= 0x4269;
Const UOBJ_SOULFORGE_SW		:= 0x426c;
Const UOBJ_SOULFORGE_SE		:= 0x426d;

Const UOBJ_ELVEN_ANVIL1		:= 0x2dd5;
Const UOBJ_ELVEN_ANVIL2		:= 0x2dd6;

Const UOBJ_SOULFORGE_ANVIL1	:= 0x4254;
Const UOBJ_SOULFORGE_ANVIL2	:= 0x4255;
Const UOBJ_SOULFORGE_ANVIL3	:= 0x4256;
Const UOBJ_SOULFORGE_ANVIL4	:= 0x4257;
Const UOBJ_SOULFORGE_ANVIL5	:= 0x426a;
Const UOBJ_SOULFORGE_ANVIL6	:= 0x426e;
Const UOBJ_SOULFORGE_ANVIL7	:= 0x4270;
Const UOBJ_SOULFORGE_ANVIL8	:= 0x4271;
Const UOBJ_SOULFORGE_ANVIL9	:= 0x427e;
Const UOBJ_SOULFORGE_ANVIL10	:= 0x4282;
Const UOBJ_SOULFORGE_ANVIL11	:= 0x4284;
Const UOBJ_SOULFORGE_ANVIL12	:= 0x4285;


///////////////////
//  assorted crafting items
///////////////////

const UOBJ_LOGS				:= 0x1BDD;
const UOBJ_LOG				:= 0x1BDD;
const UOBJ_OAKLOG 	  		:= 0x15020;
const UOBJ_ASHLOG				:= 0x15021;
const UOBJ_YEWLOG				:= 0x15022;
const UOBJ_HEARTWOODLOG				:= 0x15023;
const UOBJ_BLOODWOODLOG				:= 0x15024;
const UOBJ_FROSTWOODLOG				:= 0x15025;
const UOBJ_SUNWOODLOG				:= 0x15026;



///////////////////
//  musical instruments
///////////////////

Const UOBJ_FLUTE			:= 0x17067;
Const UOBJ_TAMBORINE		:= 0x0e9d;
Const UOBJ_TAMBORINE2		:= 0x0e9e;
Const UOBJ_LUTE				:= 0x0eb3;
Const UOBJ_LUTE2			:= 0x0eb4;
Const UOBJ_DRUM			:= 0x0e9c;
Const UOBJ_HARP			:= 0x0eb2;
Const UOBJ_STANDING_HARP		:= 0x0eb1;
Const UOBJ_BAMBOO_FLUTE		:= 0x2805;
Const UOBJ_BAMBOO_FLUTE2		:= 0x2807;
Const UOBJ_AUDCHAR			:= 0x403b;
Const UOBJ_AUDCHAR2			:= 0x403c;
Const UOBJ_FIDDLE			:= 0x420c;




///////////////////
//  leather armor
///////////////////

Const UOBJ_LEATHER_GORGET	:= 0x13C7;
Const UOBJ_LEATHER_SLEEVES	:= 0x13C5;
Const UOBJ_LEATHER_SLEEVES2	:= 0x13CD;
Const UOBJ_LEATHER_GLOVES	:= 0x13C6;
Const UOBJ_LEATHER_CAP		:= 0x1DB9;
Const UOBJ_LEATHER_LEGGINGS	:= 0x13CB;
Const UOBJ_LEATHER_TUNIC	:= 0x13CC;
Const UOBJ_LEATHER_TUNIC2	:= 0x13D3;
Const UOBJ_LEATHER_FEMALE	:= 0x1C06;
Const UOBJ_LEATHER_SKIRT	:= 0x1C08;
Const UOBJ_LEATHER_BUSTIER	:= 0x1C0A;
Const UOBJ_LEATHER_SHORTS	:= 0x1C00;




///////////////////
//  studded armor
///////////////////

Const UOBJ_STUDDED_CAP		:= 0x1708b;
Const UOBJ_STUDDED_GORGET	:= 0x13D6;
Const UOBJ_STUDDED_GLOVES	:= 0x13D5;
Const UOBJ_STUDDED_SLEEVES	:= 0x13D4;
Const UOBJ_STUDDED_SLEEVES2	:= 0x13DC;
Const UOBJ_STUDDED_LEGGINGS	:= 0x13DA;
Const UOBJ_STUDDED_TUNIC	:= 0x13DB;
Const UOBJ_STUDDED_FEMALE	:= 0x1C02;
Const UOBJ_STUDDED_BUSTIER	:= 0x1C0C;




///////////////////
//  ringmail armor
///////////////////

Const UOBJ_RINGMAIL_COIF		:= 0x1708c;
Const UOBJ_RINGMAIL_TUNIC		:= 0x13ec;
Const UOBJ_RINGMAIL_TUNIC2		:= 0x13ed;
Const UOBJ_RINGMAIL_SLEEVES		:= 0x13ee;
Const UOBJ_RINGMAIL_SLEEVES2	:= 0x13ef;
Const UOBJ_RINGMAIL_LEGGINGS	:= 0x13f0;
Const UOBJ_RINGMAIL_LEGGINGS2	:= 0x13f1;
Const UOBJ_RINGMAIL_GLOVES		:= 0x13f2;
Const UOBJ_RINGMAIL_GLOVES2		:= 0x13eb;



///////////////////
//  chainmail armor
///////////////////

Const UOBJ_CHAINMAIL_COIF		:= 0x13bb;
Const UOBJ_CHAINMAIL_COIF2		:= 0x13c0;
Const UOBJ_CHAINMAIL_LEGGINGS	:= 0x13be;
Const UOBJ_CHAINMAIL_LEGGINGS2	:= 0x13c3;
Const UOBJ_CHAINMAIL_TUNIC		:= 0x13bf;
Const UOBJ_CHAINMAIL_TUNIC2		:= 0x13c4;
Const UOBJ_CHAINMAIL_GLOVES		:= 0x17066;




///////////////////
//  Platemail armor
///////////////////

Const UOBJ_PLATE_FEMALE			:= 0x1c04;
Const UOBJ_PLATE_FEMALE2		:= 0x1c05;
Const UOBJ_PLATE_BREASTPLATE	:= 0x1415;
Const UOBJ_PLATE_BREASTPLATE2	:= 0x1416;
Const UOBJ_PLATE_ARMS			:= 0x1410;
Const UOBJ_PLATE_ARMS2			:= 0x1417;
Const UOBJ_PLATE_LEGS			:= 0x1411;
Const UOBJ_PLATE_LEGS2			:= 0x141a;
Const UOBJ_PLATE_GLOVES			:= 0x1414;
Const UOBJ_PLATE_GLOVES2		:= 0x1418;
Const UOBJ_PLATE_GORGET			:= 0x1413;




///////////////////
//  Bone armor
///////////////////

Const UOBJ_BONE_ARMS		:= 0x144e;
Const UOBJ_BONE_TUNIC		:= 0x144f;
Const UOBJ_BONE_GLOVES		:= 0x1450;
Const UOBJ_BONE_HELM		:= 0x1451;
Const UOBJ_BONE_LEGS		:= 0x1452;




///////////////////
//  Masks
///////////////////

Const UOBJ_ORC_MASK			:= 0x141B;
Const UOBJ_ORC_MASK2		:= 0x141C;
Const UOBJ_BEAR_MASK		:= 0x1545;
Const UOBJ_BEAR_MASK2		:= 0x1546;
Const UOBJ_DEER_MASK		:= 0x1547;
Const UOBJ_DEER_MASK2		:= 0x1548;
Const UOBJ_TRIBAL_MASK		:= 0x1549;
Const UOBJ_TRIBAL_MASK2		:= 0x154A;
Const UOBJ_TRIBAL_MASK3		:= 0x154B;
Const UOBJ_TRIBAL_MASK4		:= 0x154C;




///////////////////
//  helms
///////////////////

Const UOBJ_PLATE_HELM		:= 0x1412;
Const UOBJ_PLATE_HELM2		:= 0x1419;
Const UOBJ_CLOSEHELM		:= 0x1408;
Const UOBJ_CLOSEHELM2		:= 0x1409;
Const UOBJ_HELMET			:= 0x140a;
Const UOBJ_HELMET2			:= 0x140b;
Const UOBJ_BASCINET			:= 0x140c;
Const UOBJ_BASCINET2		:= 0x140d;
Const UOBJ_NOSEHELM			:= 0x140e;
Const UOBJ_NOSEHELM2		:= 0x140f;
Const UOBJ_ORCHELM			:= 0x1F0B;
Const UOBJ_ORCHELM2			:= 0x1F0C;




///////////////////
//  shields
///////////////////

Const UOBJ_BUCKLER				:= 0x1b73;
Const UOBJ_BRONZESHIELD			:= 0x1b72;
Const UOBJ_METALSHIELD			:= 0x1b7b;
Const UOBJ_KITESHIELD			:= 0x1b74;
Const UOBJ_KITESHIELD2			:= 0x1b75;
Const UOBJ_HEATER				:= 0x1b76;
Const UOBJ_HEATER2				:= 0x1b77;
Const UOBJ_WOODEN_SHIELD		:= 0x1b7a;
Const UOBJ_WOODEN_KITESHIELD	:= 0x1b78;
Const UOBJ_WOODEN_KITESHIELD2	:= 0x1b79;
Const UOBJ_CHAOS_SHIELD			:= 0x1bc3;
Const UOBJ_ORDER_SHIELD			:= 0x1bc4;
Const UOBJ_ORDER_SHIELD2		:= 0x1bc5;

Const UOBJ_G_WOODEN_SHIELD		:= 0x4200;
Const UOBJ_G_KITESHIELD			:= 0x4201;
Const UOBJ_G_SMALL_PLATESHIELD := 0x4202;
Const UOBJ_G_MEDIUM_PLATESHIELD	:= 0x4203;
Const UOBJ_G_LARGE_PLATESHIELD			:= 0x4204;
Const UOBJ_G_LARGE_STONESHIELD			:= 0x4205;
Const UOBJ_G_KITESHIELD2			:= 0x4206;
Const UOBJ_G_WOODEN_SHIELD2		:= 0x4207;
Const UOBJ_G_LARGE_PLATESHIELD2			:= 0x4208;
Const UOBJ_G_MEDIUM_PLATESHIELD2	:= 0x4209;
Const UOBJ_G_SMALL_PLATESHIELD2 := 0x420a;
Const UOBJ_G_LARGE_STONESHIELD2			:= 0x420b;
Const UOBJ_G_CHAOS_SHIELD			:= 0x4228;
Const UOBJ_G_CHAOS_SHIELD2			:= 0x4229;
Const UOBJ_G_ORDER_SHIELD			:= 0x422a;
Const UOBJ_G_ORDER_SHIELD2			:= 0x422c;



///////////////////
//  woodeden weapons
///////////////////

Const UOBJ_CLUB				:= 0x13b3;
Const UOBJ_SHEEPHERDS_CROOK	:= 0x0e81;
Const UOBJ_BLACK_STAFF		:= 0x0df0;
Const UOBJ_GNARLED_STAFF	:= 0x13f9;
Const UOBJ_MAGE_STAFF		:= 0x17065;
Const UOBJ_DRUID_STAFF		:= 0x17068;
Const UOBJ_NECRO_STAFF		:= 0x1706a;
Const UOBJ_QUARTER_STAFF	:= 0x0e8a;




///////////////////
//  Keys
///////////////////

Const UOBJ_KEY_START		:= 0x100E;
Const UOBJ_KEY_END			:= 0x1013;

Const UOBJ_COPPER_KEY		:= 0x100E;
Const UOBJ_GOLD_KEY			:= 0x100F;
Const UOBJ_IRON_KEY			:= 0x1010;
Const UOBJ_KEY_RING			:= 0x1011;
Const UOBJ_MAGIC_KEY		:= 0x1012;
Const UOBJ_RUSTY_IRON_KEY	:= 0x1013;




///////////////////
//  archery items
///////////////////

Const UOBJ_BOW				:= 0x13B2;
Const UOBJ_CROSSBOW			:= 0x0F4F;
Const UOBJ_HEAVY_CROSSBOW	:= 0x13FD;
Const UOBJ_FIRE_BOW			:= 0x16050;
const UOBJ_FEATHER			:= 0x1BD1;
const UOBJ_SHAFT			:= 0x1BD4;
Const UOBJ_ARROW			:= 0x0f3f;
Const UOBJ_BOLT				:= 0x1bfb;
Const UOBJ_FIRE_ARROW		:= 0x16051;
Const UOBJ_FROST_ARROW		:= 0x16052;
Const UOBJ_FIRE_BOLT		:= 0x16053;
Const UOBJ_FROST_BOLT		:= 0x16054;



Const UOBJ_COMPOSITE_BOW		:= 0x26C2;
Const UOBJ_REPEATING_CROSSBOW	:= 0x26C3;
Const UOBJ_YUMI					:= 0x27F0;
Const UOBJ_LONGBOW				:= 0x2D2A;
Const UOBJ_SHORTBOW				:= 0x2D2B;
const UOBJ_HEAVY_XBOW			:= 0x13fd;
const UOBJ_DART_THROWER := 0x27f5;
Const UOBJ_DART				:= 0x2804;
Const UOBJ_FIRE_DART		:= 0x16055;
Const UOBJ_FROST_DART		:= 0x16056;
const UOBJ_SHURIKEN_THROWER := 0x2790;
Const UOBJ_SHURIKEN				:= 0x27ac;
Const UOBJ_FIRE_SHURIKEN		:= 0x16057;
Const UOBJ_FROST_SHURIKEN		:= 0x16058;
const UOBJ_AXE_THROWER := 0x27DB;
Const UOBJ_THROWINGAXE				:= 0x255d;
Const UOBJ_FIRE_THROWINGAXE		:= 0x16059;
Const UOBJ_FROST_THROWINGAXE		:= 0x1605a;



///////////////////
// Some weapons
///////////////////

Const UOBJ_FIST				:= 0x1F020;
Const UOBJ_DAGGER			:= 0x0f51;
Const UOBJ_SKINNING_KNIFE	:= 0x0ec4;




///////////////////
//  Food items
///////////////////

Const UOBJ_EGG				:= 0x09b5;
Const UOBJ_RAW_RIB			:= 0x09f1;
Const UOBJ_RAW_FISHSTEAK	:= 0x097a;
Const UOBJ_RAW_BIRD			:= 0x09b9;
Const UOBJ_RAW_HAM			:= 0x09c9;
Const UOBJ_BACON_SLAB		:= 0x0976;
Const UOBJ_RAW_SAUSAGE		:= 0x09c0;
Const UOBJ_HONEY			:= 0x09ec;
Const UOBJ_CARROT			:= 0x0c77;
Const UOBJ_APPLE			:= 0x09d0;
Const UOBJ_PEACH			:= 0x172c;
Const UOBJ_LEMON			:= 0x1728;
Const UOBJ_LIME				:= 0x172a;
Const UOBJ_BANANA			:= 0x171f;
Const UOBJ_PEAR				:= 0x172d;
Const UOBJ_GRAPES			:= 0x0d1a;
Const UOBJ_DATES			:= 0x1727;
Const UOBJ_PUMPKIN			:= 0x0c6a;
Const UOBJ_LETTUCE			:= 0x0c70;
Const UOBJ_CABBAGE			:= 0x0c7c;
Const UOBJ_ONION			:= 0x0c6d;
Const UOBJ_TURNIP			:= 0x0d3a;
Const UOBJ_COCONUT			:= 0x1726;
Const UOBJ_RAW_CHICKEN_LEG	:= 0x1607;
Const UOBJ_RAW_LEG_OF_LAMB	:= 0x1609;




///////////////////
//  Mining items
///////////////////

const UOBJ_SHOVEL				:= 0x0F39;
const UOBJ_IRON_SHOVEL			:= 0x17091;
const UOBJ_BRONZE_SHOVEL		:= 0x17092;
const UOBJ_DULL_COPPER_SHOVEL	:= 0x17093;
const UOBJ_COPPER_SHOVEL		:= 0x17094;
const UOBJ_ONYX_SHOVEL			:= 0x17095;
const UOBJ_PYRITE_SHOVEL		:= 0x17096;
const UOBJ_MALACHITE_SHOVEL		:= 0x17097;
const UOBJ_AZURITE_SHOVEL		:= 0x17098;
const UOBJ_RUBYSTEEL_SHOVEL		:= 0x17099;
const UOBJ_BLUESTEEL_SHOVEL		:= 0x1709a;





///////////////////
//  Maps
///////////////////

const UOBJ_DECODED_MAP		:= 0x14EB;
const UOBJ_LEVEL_1_MAP		:= 0x16003;
const UOBJ_LEVEL_2_MAP		:= 0x16004;
const UOBJ_LEVEL_3_MAP		:= 0x16005;
const UOBJ_LEVEL_4_MAP		:= 0x16006;
const UOBJ_LEVEL_5_MAP		:= 0x16007;
const UOBJ_SEER_MAP			:= 0x16008;





/////////////////////////////
//  Other items that probably should get sorted
/////////////////////////////


const UOBJ_LOOM_START		:= 0x105F;
const UOBJ_LOOM_END			:= 0x1066;
Const UOBJ_MOUNT			:= 0x1f021;

const UOBJ_DUMMYSWING_NS    := 0x1071;
const UOBJ_DUMMYFREEZE_NS   := 0x1070;
const UOBJ_DUMMYSWING_EW    := 0x1075;
const UOBJ_DUMMYFREEZE_EW   := 0x1074;

Const STARTHAIR				:= 0x203b;
Const ENDHAIR				:= 0x204d;
Const UOBJ_STARTHAIR		:= 0x203b;
Const UOBJ_ENDHAIR			:= 0x204d;

const UOBJ_BLOOD        := 0x122D;

const UOBJ_MAP1         := 0x14EB;
const UOBJ_MAP2         := 0x14EC;
const UOBJ_ROLLED_MAP1  := 0x14ED;
const UOBJ_ROLLED_MAP2  := 0x14EE;

const UOBJ_HOUSE_DEED1  := 0x14ef;
const UOBJ_SHIP_DEED1   := 0x14F1;
const UOBJ_SHIP_DEED2   := 0x14F2;

const UOBJ_CHEST        := 0x1940;


const UOBJ_ARM          := 0x1DA1;
const UOBJ_LEG          := 0x1DA3;
const UOBJ_TRUNK        := 0x1D9F;
const UOBJ_HEART        := 0x1CED;
const UOBJ_HEAD         := 0x1DA0;
const UOBJ_LEFTARM	:= 0x1DA1;
const UOBJ_RIGHTARM	:= 0x1DA2;
const UOBJ_LEFTLEG	:= 0x1DA3;
const UOBJ_RIGHTLEG	:= 0x1DA4;
const UOBJ_LIVER	:= 0x1CEE;
const UOBJ_ENTRAILS	:= 0x1CEF;
const UOBJ_BRAIN	:= 0x1CF0;

const UOBJ_CORPSE       := 0x2006;

const UOBJ_PARAFIELD_NS := 0x3967;
const UOBJ_PARAFIELD_EW := 0x3979;
const UOBJ_POISONFIELD_NS   := 0x3914;
const UOBJ_POISONFIELD_EW   := 0x3920;
const UOBJ_EFIELD_NS        := 0x3947;
const UOBJ_EFIELD_EW        := 0x3956;

const GID_PLANK_EXTENDED_FACING_WEST   := 0x3ed5;
const GID_PLANK_RETRACTED_FACING_WEST  := 0x3eb1;
const GID_PLANK_EXTENDED_FACING_EAST   := 0x3ed4;
const GID_PLANK_RETRACTED_FACING_EAST  := 0x3eb2;
const GID_PLANK_EXTENDED_FACING_SOUTH  := 0x3e84;
const GID_PLANK_RETRACTED_FACING_SOUTH := 0x3e85;
const GID_PLANK_EXTENDED_FACING_NORTH  := 0x3e89;
const GID_PLANK_RETRACTED_FACING_NORTH := 0x3e8a;

// ick! these are fine for humans, but not true for items..
// these are more of a CID.
const UOBJ_HUMAN_MALE   := 0x190;
const UOBJ_HUMAN_FEMALE := 0x191;






const UOBJ_STONEWALL_NS := 0x005f;
const UOBJ_STONEWALL_EW := 0x0057;

const UOBJ_FISHSTEAK    := 0x097A;

const UOBJ_BOX          := 0x09aa;

const UOBJ_FISH_START   := 0x09CC;
const UOBJ_FISH_END     := 0x09CF;
Const UOBJ_SPLASH_TILE	:= 0x1706c;

const UOBJ_SFISH_START  := 0x0DD6;
const UOBJ_SFISH_END    := 0x0DD9;

const UOBJ_KINDLING     := 0x0DE1;
const UOBJ_CAMPFIRE     := 0x0DE3;   
const UOBJ_EMBERS       := 0x0DE9;       
const UOBJ_ASHES        := 0x0DEA;

const UOBJ_BANDAGE      := 0x0E21;
const UOBJ_BLANK_SCROLL := 0x0E34;

const UOBJ_BANKBOX      := 0x0E7C;
const UOBJ_EMPTY_BOTTLE     := 0x0F0E;


const UOBJ_LOCKPICKS    := 0x14fb;

const UOBJ_BLUE_MOONGATE    := 0x0F6C;
Const UOBJ_SPIDERWEB := 0xbf01;

const UOBJ_CONTRACT_BLACKSMITHY := 0x170d0;




/////////////////////////////////////////////////////////////////////////////
//
// 0x1F000 to 0x1FFFF - Reserved by system
//
/////////////////////////////////////////////////////////////////////////////

	//
	// Ship Components
	//
const EXTOBJ_TILLERMAN       := 0x1F010;
const EXTOBJ_PORT_PLANK      := 0x1F011;
const EXTOBJ_STARBOARD_PLANK := 0x1F012;
const EXTOBJ_HOLD            := 0x1F013;

